---
title: "Final Project Report"
author: "Hunter Fristick"
date: "Due: 12/15/2021"
output: html_notebook
---

# Set Up

### Clean up environment and load packages
```{r}
# clean up the RStudio environment 
rm(list = ls())

# load all packages here: 
library(mosaic)
library(tidyr)
library(rvest)

```

### Data Access

```{r}
Salaries <- readr::read_csv('C:\\Users\\frist\\OneDrive\\Documents\\Penn State\\STAT 184\\Github Repository\\final-project-report-fristick\\Salaries.csv')
```

```{r}
web_page <- "https://www.baseball-reference.com/leagues/NL/#teams_team_wins3000"
SetOfTables <- web_page %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)

NLWinsandLosses <- SetOfTables[[1]]
```

```{r}
web_pageAL <- "https://www.baseball-reference.com/leagues/AL/#teams_team_wins3000"
SetOfTables <- web_pageAL %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)

ALWinsandLosses <- SetOfTables[[1]]
```

```{r}
head(Salaries)
```


```{r}
head(NLWinsandLosses)
```

```{r}
summary(ALWinsandLosses)
```

```{r}
summary(Salaries)
```

### Data Wrangling / Cleaning

```{r}
 NLWinsLonger <-
    NLWinsandLosses %>%
    pivot_longer(cols = c(ARI, ATL, CHC, CIN, COL, HOU, LAD, MIA, MIL, NYM, PHI, PIT, SDP, SFG, STL, WSN), names_to = "Team", values_to = "Wins")

ALWinsLonger <-
    ALWinsandLosses %>%
    pivot_longer(cols = c(BAL, BLA, BOS, CHW, CLE, DET, HOU, KCR, LAA, MIL, MIN, NYY, OAK, SEA, TBR, TEX, TOR), names_to = "Team", values_to = "Wins")

WinsLonger <- rbind(NLWinsLonger, ALWinsLonger)
```



```{r}
HighestWinsbyYear <-
  WinsLonger %>%
  group_by(Year) %>%
  filter(Year >= 1985 & Year <= 2016 & Year != 'Year') %>%
  summarise(MostWins = max(Wins), Team)
  
HighestWinsbyYear
```
```{r}
SalSum <-
  Salaries %>%
  group_by(yearID = as.character(yearID), teamID) %>%
  summarise(totalSal = sum(salary))
SalSum
```

```{r}
JoinedData <-
  SalSum %>%
  inner_join(WinsLonger, by = c("yearID" = "Year", "teamID" = "Team"))

JoinedData
```


### Data Visualization


